<a href="https://colab.research.google.com/github/NovVitaliy/VKN/blob/main/%D0%9B%D0%A01_%D0%9D%D0%BE%D0%B2%D0%BE%D1%85%D0%B0%D1%86%D1%8C%D0%BA%D0%B8%D0%B9_4_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.

##Роботу виконав
Новохацький ФІТ 4-9

## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [1]:
# Код студента
import numpy as np
print('Version NumPy', np.__version__)

Version NumPy 2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [2]:
arr1 = np.array([2, 4, 6, 8, 10])
print(arr1)
print(type(arr1))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [ ]:
# Код студента
arr2 = np.zeros(10, dtype=int)
arr3 = np.ones(8, dtype=int)
arr67 = np.full(6, 7)

print(arr2)
print(arr3)
print(arr67)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1]
[7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
# Код студента
arr_1_20 = np.arange(1, 21)
print (arr_1_20)
arr_step2 = np.arange(2, 21, 2)
print(arr_step2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
# Код студента
arr_01 = np.linspace(0, 1, 11)
print(arr_01)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:
# Код студента
mat_34 = np.arange(1, 13).reshape(3, 4)
print(mat_34)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:
# Код студента
print('Кількість вимірів -', mat_34.ndim)
print('Форма матриці -', mat_34.shape)
print('Кількість елементів матриці -', mat_34.size)
print('Тип даних елеметів матриці -', mat_34.dtype)

Кількість вимірів - 2
Форма матриці - (3, 4)
Кількість елементів матриці - 12
Тип даних елеметів матриці - int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [ ]:
# Код студента
arr4 = np.array([1.2, 3.5, 5.7, 7.9])
arr_int = arr4.astype(int)
print(arr_int)

[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [ ]:
# Код студента
arr_10 = np.arange(10, 90, 10)
print(arr_10)
print(arr_10[0])
print(arr_10[-1])
print(arr_10[2:6])
print(arr_10[::2])

[10 20 30 40 50 60 70 80]
10
80
[30 40 50 60]
[10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [ ]:
# Код студента
mat_34 = np.arange(1, 13).reshape(3, 4)
print('елемент 7 --', mat_34[1, 2])
print('другий рядок --', mat_34[1, :])
print('третій стовпець --', mat_34[:, 2])
print('підматриця --', mat_34[-2:, :2])

елемент 7 -- 7
другий рядок -- [5 6 7 8]
третій стовпець -- [ 3  7 11]
підматриця -- [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [ ]:
# Код студента
arr5 = np.arange(1, 16)
arr5[5:10] = 0
print(arr5)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [ ]:
# Код студента
arr_a = np.arange(1, 6)
arr_b = np.arange(10, 60, 10)

print('сума масивів', arr_a + arr_b)
print('різниця масивів', arr_a - arr_b)
print('добуток масивів', arr_a * arr_b)
print('ділення масивів', arr_a / arr_b)

сума масивів [11 22 33 44 55]
різниця масивів [ -9 -18 -27 -36 -45]
добуток масивів [ 10  40  90 160 250]
ділення масивів [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [ ]:
# Код студента
arr6 = np.array([4, 8, 15, 16, 23, 42])
print('сума --', np.sum(arr6))
print('середнє значення --', np.mean(arr6))
print('мінімум --', np.min(arr6))
print('максимум --', np.max(arr6))
print('медіана --', np.median(arr6))
print('стандартне відхиленя --', np.std(arr6))

сума -- 108
середнє значення -- 18.0
мінімум -- 4
максимум -- 42
медіана -- 15.5
стандартне відхиленя -- 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [ ]:
# Код студента
mat_33 = np.arange(1, 10).reshape(3, 3)
print(np.sum(mat_33))
print(np.sum(mat_33, axis=0))
print(np.sum(mat_33, axis=1))
print(np.mean(mat_33, axis=0))

45
[12 15 18]
[ 6 15 24]
[4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [ ]:
# Код студента
arr7 = np.arange(1, 11)
print(np.square(arr7))
print(np.sqrt(arr7))
print(np.log(arr7))

[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [ ]:
# Код студента
arr8 = np.array([3, 7, 12, 18, 21, 25, 30, 34])
print(arr8[arr8 > 15])
print(arr8[arr8 % 2 == 0])
print(arr8[(arr8 >= 10) & (arr8 <= 30)])

[18 21 25 30 34]
[12 18 30 34]
[12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
arr9 = np.array([-5, 3, -2, 8, -1, 10, 0])
arr9[arr9 < 0] = 0
print(arr9)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [ ]:
# Код студента
np.random.seed(42)
arr10 = np.random.randint(0, 101, 20)
print(arr10)
print(arr10[arr10 > 50])
print(arr10[arr10 <= 50])

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
[51 92 71 60 82 86 74 74 87 99 52 87]
[14 20 23  2 21  1 29 37]


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [ ]:
# Код студента
arr11 = np.arange(1, 25)
print(arr11)
mat_46 = arr11.reshape(4, 6)
print(mat_46.shape)
mat_64 = arr11.reshape(6, 4)
print(mat_64.shape)
mat_234 = arr11.reshape(2, 3 ,4)
print(mat_234.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(4, 6)
(6, 4)
(2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [ ]:
# Код студента
mat_A = np.arange(1, 5).reshape(2, 2)
mat_B = np.arange(5, 9).reshape(2, 2)
print(np.vstack((mat_A, mat_B)))
print(np.vstack((mat_A, mat_B)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [ ]:
# Код студента
mat_34 = np.arange(1, 13).reshape(3, 4)
arr12 = mat_34.flatten()
arr13 = mat_34.ravel()
print(arr12)
print(arr13)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [ ]:
# Код студента
arra = np.array([2, 4, 6])
arrb = np.array([1, 3, 5])
print('сума векторів --', arra + arrb)
print('різниця векторів --', arra - arrb)
print('множення a * 3--', arra * 3)
print('множення b * 3--', arrb * 3)

сума векторів -- [ 3  7 11]
різниця векторів -- [1 1 1]
множення a * 3-- [ 6 12 18]
множення b * 3-- [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [ ]:
# Код студента
arra = np.array([2, 4, 6])
arrb = np.array([1, 3, 5])
print('np.dot() --', np.dot(arra, arrb))
print('@ --', arra @ arrb)

np.dot() -- 44
@ -- 44


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:
# Код студента
arr_v = np.array([3, 4])
arr_normV = np.linalg.norm(arr_v)
print('evklid norm --', arr_normV)
print('normalize vector --', arr_v / arr_normV)

evklid norm -- 5.0
normalize vector -- [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [ ]:
# Код студента
arr__a = np.array([1, 0, 0])
arr__b = np.array([0, 1, 0])
print(np.cross(arr__a, arr__b))

[0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [ ]:
# Код студента
arra1 = np.array([1, 2])
arrb1 = np.array([2, 1])

cos_arra1_arrb1 = np.dot(arra1, arrb1) / (np.linalg.norm(arra1) * np.linalg.norm(arrb1))
angle_rad = np.arccos(cos_arra1_arrb1)
angle_deg = np.degrees(angle_rad)

print(cos_arra1_arrb1)
print(angle_deg)

0.7999999999999998
36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [ ]:
# Код студента
matA = np.arange(1, 7).reshape(2, 3)
print(matA)
print('.T --', matA.T)
print('np.transpose --', np.transpose(matA))

[[1 2 3]
 [4 5 6]]
.T -- [[1 4]
 [2 5]
 [3 6]]
np.transpose -- [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [ ]:
# Код студента
matrA = np.arange(1, 5).reshape(2, 2)
matrB = np.array([[2, 0], [1, 2]])
print('Поелемнтний добуток --', matrA * matrB)
print('Матричний добуток--', matrA @ matrB)

Поелемнтний добуток -- [[2 0]
 [3 8]]
Матричний добуток-- [[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [ ]:
# Код студента
matrxA = np.array([[4, 7], [2, 6]])
det_A = np.linalg.det(matrxA)
inv_A = np.linalg.inv(matrxA)

print('det_A --', det_A)
print('inv_A --', inv_A)
print('matrxA * inv_A --', matrxA @ inv_A)

det_A -- 10.000000000000002
inv_A -- [[ 0.6 -0.7]
 [-0.2  0.4]]
matrxA * inv_A -- [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [ ]:
# Код студента
arr14 = np.array([[2, 1], [1, 3]])
arr15 = np.array([5, 6])
x = np.linalg.solve(arr14, arr15)
print(x)

[1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [ ]:
# Код студента
matrix_1 = np.eye(4)
matrix_rand = np.random.randint(10, 21, (4, 4))

result = matrix_1 @ matrix_rand

print("одинична матриця --", matrix_1)
print("довільна матриця --", matrix_rand)
print("результат множення --", result)
print("рівні матриці?", np.allclose(matrix_rand, result))

одинична матриця -- [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
довільна матриця -- [[11 17 18 11]
 [14 17 12 11]
 [15 17 19 15]
 [16 18 11 13]]
результат множення -- [[11. 17. 18. 11.]
 [14. 17. 12. 11.]
 [15. 17. 19. 15.]
 [16. 18. 11. 13.]]
рівні матриці? True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [3]:
# Код студента
arra2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arra2 + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [7]:
# Код студента
arra2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = np.array([10, 20, 30])

print("Результат A + v:\n", arra2 + v)

# Аналіз broadcasting:
# NumPy автоматично "розтягує" одновимірний масив (вектор v)
# так, щоб додати його до кожного рядка двовимірного масиву (матриці A).

Результат A + v:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [8]:
# Код студента
arra3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

mu = np.mean(arra3, axis=0)
sigma = np.std(arra3, axis=0)
z = (arra3 - mu) / sigma

print("Нормалізована матриця --", z)

Нормалізована матриця -- [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [11]:
# Код студента
np.random.seed(42)

rand_ints = np.random.randint(1, 101, 10)
rand_matrix = np.random.rand(3, 3)
norm_dist = np.random.randn(1000)

print("Випадкові цілі числа --", rand_ints)
print("Випадкова матриця 3x3 --", rand_matrix)
print("Середнє нормального розподілу --", np.mean(norm_dist))
print("Стандартне відхилення нормального розподілу --", np.std(norm_dist))

Випадкові цілі числа -- [52 93 15 72 61 21 83 87 75 75]
Випадкова матриця 3x3 -- [[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Середнє нормального розподілу -- 0.02216865975826456
Стандартне відхилення нормального розподілу -- 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [19]:
# Код студента
grades = np.random.randint(0, 101, 30)

print("Оцінки --", grades)
print("Середня оцінка --", np.mean(grades))
print("Медіана --", np.median(grades))
print("Найвища оцінка --", np.max(grades))
print("Найнижча оцінка --", np.min(grades))
print("Кількість студентів (>= 60) --", np.sum(grades >= 60))
print("Відсоток студентів (>= 90) --", np.mean(grades >= 90) * 100, "%")

Оцінки -- [16 25  7 46 75 90 71 88 45 67 32  0 18 30 79 13 52 47 68 89 61 91 65 63
 69 62 72 32 40 88]
Середня оцінка -- 53.36666666666667
Медіана -- 61.5
Найвища оцінка -- 91
Найнижча оцінка -- 0
Кількість студентів (>= 60) -- 16
Відсоток студентів (>= 90) -- 6.666666666666667 %


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [20]:
# Код студента
arr_sales = np.array([[120, 150, 170, 160], [80, 90, 100, 110], [200, 180, 210, 230]])

total_per_product = np.sum(arr_sales, axis=1)
total_per_month = np.sum(arr_sales, axis=0)

print("Загальний обсяг продажів кожного товару --", total_per_product)
print("Загальний обсяг продажів у кожному місяці --", total_per_month)
print("Товар із найбільшими продажами (індекс) --", np.argmax(total_per_product))
print("Місяць із найбільшим обсягом продажів (індекс) --", np.argmax(total_per_month))
print("Середній обсяг продажів кожного товару --", np.mean(arr_sales, axis=1))

Загальний обсяг продажів кожного товару -- [600 380 820]
Загальний обсяг продажів у кожному місяці -- [400 420 480 500]
Товар із найбільшими продажами (індекс) -- 2
Місяць із найбільшим обсягом продажів (індекс) -- 3
Середній обсяг продажів кожного товару -- [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [30]:
# Код студента
arrM = np.random.randint(1, 21, (5, 5)) #[cite: 1]
print(arrM)

print("Сума головної діагоналі --", np.trace(arrM))
print("Сума побічної діагоналі --", np.trace(np.fliplr(arrM)))
print("Максимальний елемент кожного рядка --", np.max(arrM, axis=1))
print("Мінімальний елемент кожного стовпця --", np.min(arrM, axis=0))

mean_val = np.mean(arrM)
arrM[arrM < mean_val] = 0
print(f"Матриця після заміни елементів < {mean_val:.2f} на 0 --", arrM)

[[ 8  5 20  8 12]
 [ 1 20  6 18  8]
 [ 7  1 16 12  6]
 [20  2 14  4  1]
 [18 13  2  9  2]]
Сума головної діагоналі -- 50
Сума побічної діагоналі -- 66
Максимальний елемент кожного рядка -- [20 20 16 20 18]
Мінімальний елемент кожного стовпця -- [1 1 2 4 1]
Матриця після заміни елементів < 9.32 на 0 -- [[ 0  0 20  0 12]
 [ 0 20  0 18  0]
 [ 0  0 16 12  0]
 [20  0 14  0  0]
 [18 13  0  0  0]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [31]:
# Код студента
arrx = np.array([[2, 4, 6], [1, 3, 5], [5, 7, 9]])

dist_1_2 = np.linalg.norm(arrx[0] - arrx[1])
dist_1_3 = np.linalg.norm(arrx[0] - arrx[2])
dist_2_3 = np.linalg.norm(arrx[1] - arrx[2])

print("Відстань між 1 і 2 рядком --", dist_1_2)
print("Відстань між 1 і 3 рядком --", dist_1_3)
print("Відстань між 2 і 3 рядком --", dist_2_3)

Відстань між 1 і 2 рядком -- 1.7320508075688772
Відстань між 1 і 3 рядком -- 5.196152422706632
Відстань між 2 і 3 рядком -- 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [36]:
# Код студента
arr44 = np.random.randint(0, 101, (4, 4))
print(arr44)

row_norms = np.linalg.norm(arr44, axis=1, keepdims=True)

normalized_arr44 = arr44 / row_norms

print("Нормалізована матриця --", normalized_arr44)

[[40  5 24 12]
 [97  7 20 97]
 [67 24 78 67]
 [44 59 11 31]]
Нормалізована матриця -- [[0.82601621 0.10325203 0.49560972 0.24780486]
 [0.69881897 0.05043023 0.14408639 0.69881897]
 [0.53577716 0.19192018 0.62374058 0.53577716]
 [0.54579482 0.73186123 0.1364487  0.38453726]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [37]:
# Код студента
arrA4 = np.array([[1,  2,  1], [2,  1, -1], [3, -1,  2]])
arrb4 = np.array([9, 8, 3])

x_solve = np.linalg.solve(arrA4, arrb4)

print("Розв'язок системи --", x_solve)
print("Перевірка (A @ x) --", arrA4 @ x_solve)
print("Порівняння з вектором b --", np.allclose(arrA4 @ x_solve, arrb4))

Розв'язок системи -- [ 2.22222222  3.44444444 -0.11111111]
Перевірка (A @ x) -- [9. 8. 3.]
Порівняння з вектором b -- True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
